// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5V5Enznv8YB-qiGyabaoVInxD6r7A3M',
    appId: '1:653784877898:web:0adde4b63dc98048364fb3',
    messagingSenderId: '653784877898',
    projectId: 'medisync-17bfa',
    authDomain: 'medisync-17bfa.firebaseapp.com',
    databaseURL: 'https://medisync-17bfa-default-rtdb.firebaseio.com',
    storageBucket: 'medisync-17bfa.appspot.com',
    measurementId: 'G-555M651RYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCv5lZ8i-sPPEjwCdCQtD51jIzrwseOo',
    appId: '1:653784877898:android:8bd70e63882bc02f364fb3',
    messagingSenderId: '653784877898',
    projectId: 'medisync-17bfa',
    databaseURL: 'https://medisync-17bfa-default-rtdb.firebaseio.com',
    storageBucket: 'medisync-17bfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACjzd8Vlw7V42yWR57txId_x5abz04n-o',
    appId: '1:653784877898:ios:682a61ecebd9fa14364fb3',
    messagingSenderId: '653784877898',
    projectId: 'medisync-17bfa',
    databaseURL: 'https://medisync-17bfa-default-rtdb.firebaseio.com',
    storageBucket: 'medisync-17bfa.appspot.com',
    iosBundleId: 'com.example.medsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACjzd8Vlw7V42yWR57txId_x5abz04n-o',
    appId: '1:653784877898:ios:682a61ecebd9fa14364fb3',
    messagingSenderId: '653784877898',
    projectId: 'medisync-17bfa',
    databaseURL: 'https://medisync-17bfa-default-rtdb.firebaseio.com',
    storageBucket: 'medisync-17bfa.appspot.com',
    iosBundleId: 'com.example.medsync',
  );
}
